#!/usr/bin/env bash

PATH=$BOUNCER/bin:$BOUNCER/script:$PATH

# ensure output dir exists
mkdir -p $BOUNCER/output

# ANSI color codes
AC_NONE=$'\033[0m'
AC_GREEN=$'\033[1;32m'
AC_CYAN=$'\033[1;36m'
AC_RED=$'\033[1;31m'
AC_BLUE=$'\033[1;34m'
AC_YELLOW=$'\033[1;33m'
AC_WHITE_RED=$'\033[1;37m\033[41m'

PASS="${AC_GREEN}PASS${AC_NONE}"
FAIL="${AC_RED}FAIL${AC_NONE}"

