#!/usr/bin/env bash

PATH=$PEC/bin:$PATH

# ensure output dir exists
mkdir -p $PEC/output

# ANSI color codes
AC_NO=$'\033[0m'
AC_GR=$'\033[1;32m'
AC_CY=$'\033[1;36m'
AC_RD=$'\033[1;31m'
AC_BL=$'\033[1;34m'
AC_YL=$'\033[1;33m'
AC_WR=$'\033[1;37m\033[41m'

PASS="${AC_GR}PASS${AC_NO}"
FAIL="${AC_RD}FAIL${AC_NO}"

